extends:
  - '@commitlint/config-conventional'

rules:
  type-enum:
    - 2  # level: error
    - always
    - - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test

  scope-empty:
    - 0  # level: disabled

  subject-empty:
    - 2  # level: error
    - never

  subject-full-stop:
    - 2
    - never
    - '.'

  subject-case:
    - 0

  header-max-length:
    - 2
    - always
    - 100

  body-leading-blank:
    - 1  # level: warning
    - always

  footer-leading-blank:
    - 1
    - always
